name: tests-lint

on:
  push:
    branches:
      - '**'
      
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Installation
        run: make install

      - name: Run tests
        run: make test
        
      - name: Run linter
        run: make lint
